language: python
python:
  - '2.7'

env:
  global:
    - BS_PIP_ALLOWED=1
    - BS_ECHO_DEBUG=1

install:
  # Since LXC is not supported on travis OpenVZ, we disable it before
  # installation.
  - sudo make setup
  - sudo salt-call --local --grains

script:
  - sudo make test-ci
